services:
  - type: web
    name: django-chat
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn chat_project.asgi:application -b 0.0.0.0:$PORT -w 4 -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: PORT
        value: 8000 